### ISSUE TITLE
How can I make requests to WCVP as a web programmer?

### ISSUE THREAD

**Issue by stevespages** [barnabywalker/kewr#41]
First of all apologies if this is a bit off topic but I would be very grateful if you can help. I have been struggling to find any means to use WCVP (or other plant name collections) from within a Web application. Your kewr  seems to be the closest thing I have seen but I have no experience of R.

The sort of thing I would like to be able to do is: If a user of my webisite enters a scientific name of a plant into an HTML form and submits it I would like my program to be able to check with WCVP whether that scientific name is an accepted name or a synonym or simply not in the WCVP database. If the name is a synonym I would like my request to WCVP to return the Accepted name for that synonym which I could then use in my program instead of using the synonym that the user entered. That way the data accumulated by my site would stick to accepted names which I would like.

I feel sure that there must be some public facing service of this sort for the WCVP but I can find nothing about it using various google searches. From the little I can understand of your kewr system it seems possible that it could provide the functionality I am looking for but I feel it probably is not designed for the sort of use case I am interested in.

**Comment by barnabywalker** [comment]
Hi Steve, thanks for getting in touch.

There's currently no public-facing API for WCVP. 

The _kewr_ package provides an interface to WCVP for people using the R programming language. You could potentially use this in the web app you want to make, but it would involve using R in the backend somehow. I know it's possible but probably not what you want to do.

If you really wanted, you could look at the requests that this package makes and adapt them to whatever framework you want to use on your backend. However, I would check that this does not contravene the terms of service of WCVP. It looks like WCVP is shared under a CC BY 2.0 license, so I think it would be fine as long as you attribute WCVP and Kew prominently enough. But check the [WCVP website](https://wcvp.science.kew.org/).

If you need more info, I'd suggest getting in contact with bi@kew.org.

I hope that helps.

**Comment by stevespages** [comment]
Hi, thanks for your help. I have now downloaded the wcvp csv database and
used it to create a table in an SQLite database. I can access that table
from my website. Of course updates to wcvp will not be available to my
website unless I recreate the table periodically. I have assumed this would
be within the terms of wcvp but do not underestand the terms well. My
website is not commercial at the moment.

Best wishes Steve

**Comment by barnabywalker** [comment]
I would double-check the terms so you understand them before making your website live.

It sounds like you wouldn't be breaking them - I think the main thing is to put acknowledgement and a link to WCVP on your page, and it probably helps that it isn't commercial.

But I can't speak for the developers/maintainers/owners of WCVP, so you might get an email from them at some point in the future.

I'll close this now, as it seems like you've found a solution for what you needed.
