### ISSUE TITLE
Search multiple taxon names using search_powo()

### ISSUE THREAD

**Issue by jgomezd** [barnabywalker/kewr#59]
Hi Barnaby,

I want to look up a list of species using the search_powo function.

When I submitted the species list, I got the following error:
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'query_length' not found

An example:

names <- c("Myrcia guianensis", "Bad plant", "Poa annua")
search_powo(names, filters=c("species")) %>% tidy()

Could you help me?

**Comment by barnabywalker** [comment]
The `search_powo` function is a wrapper around POWO's search API, which only allows a single query at a time.

If you want multiple searches, I would suggest using a for-loop or an apply function, e.g.
```
queries <- c("Myrcia guianensis", "Bad plant", "Poa annua")
names <- lapply(names, function(x) search_powo(x, filters="species"))
tidied_names <- lapply(names, tidy)
bind_rows(tidied_names)
```

Just note, you probably don't want to search for a large number of taxa at once - there is a minimum wait time between requests so it will take a long time. You're better off widening the search to e.g. genus or matching your name list against the WCVP (the taxomic backbone behind POWO). You can use [rWCVP](https://github.com/matildabrown/rWCVP) to help with the latter.
