### ISSUE TITLE
Not the corresponding accepted species using search_powo()

### ISSUE THREAD

**Issue by MjGSob01** [barnabywalker/kewr#62]
When you search something like the following line
`kewr::search_powo("Sphagnum", filters=c("genera","accepted")`

The ouput of the accepted names for this species are Orchidaceae ones, which don't correspond to _Sphagnum_, since it is a moss genus,

When I searched in POWO, I noticed that in the description of the orchid species that are in the out have mentioned "Sphagnum" in the "General" section (see the image below).
![image](https://github.com/barnabywalker/kewr/assets/158539463/ffe7b10d-1e97-4dc2-8e70-d03b1fdcdeee)

I hope there is a way that it could be solved, since there is a huge taxonomical difference between them. Thank you so much.

**Comment by barnabywalker** [comment]
Thanks for using the package!

Searching on WCVP is a bit confusing - if your just put in a search term it will search the whole text of a taxon entry for an exact match. To search for a particular genus or species, you’re best following the advice of this help page (https://barnabywalker.github.io/kewr/articles/WCVP.html) and doing `search_wcvp(list(genus=‘sphagnum’), filters=c(‘accepted’, ‘species’))`. 

Also, WCVP is a checklist of vascular plants, so I’d be surprised if you get any results for Sphagnum (a miss, which is non-vascular).

**Comment by MjGSob01** [comment]
Thank you so much for your quick response! 
I've tried using the search_wcvp() function, but, unlike the search_powo function, it throws an "Error: API did not return json".

**Comment by barnabywalker** [comment]
Sorry, I should have said `search_powo` in my answer above. POWO is backed by WCVP, so still only contains vascular plants.

I think the WCVP api has been disabled, so I need to deprecate `search_wcvp`.

If you want to use WCVP directly, I recommend the [rWCVP](https://matildabrown.github.io/rWCVP/) package. But again, this will not contain mosses because they are not vascular plants.

**Comment by pfrombris** [comment]
Thanks for all the messages, but they don't seem to address the issue I raised, which is  #61. 

kind regards,

Peter

***@***.***



2 Feb 2024, 15:04 by ***@***.***:
